import React from 'react';
import { createRoot } from 'react-dom/client';
import { QueryClient, QueryClientProvider, useQuery, useQueryClient } from '@tanstack/react-query';
import './index.css';

const DEMO_ACCOUNT = '00000000-0000-0000-0000-000000000001';
const api = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8001';
type Point = { bucket:string; billable_calls:number };
const money=(cents:number)=>`${Math.trunc(cents/100)}.${String(cents%100).padStart(2,'0')}`;
async function fetchJson(path:string) { const r=await fetch(api+path,{headers:{'X-Dashboard-Token':sessionStorage.getItem('dashboardToken')??''}}); if(!r.ok) throw new Error('Unable to load data'); return r.json(); }
function App() {
  const queryClient=useQueryClient();
  const [dashboard,setDashboard]=React.useState(sessionStorage.getItem('dashboardToken')??'');
  const [account,setAccount]=React.useState(DEMO_ACCOUNT);
  const params=new URLSearchParams(location.search);
  const [granularity,setGranularity] = React.useState(params.get('g') === 'day' ? 'day' : 'hour');
  const [startValue,setStartValue]=React.useState(params.get('start') ?? new Date(Date.now()-24*60*60*1000).toISOString().slice(0,16));
  const [endValue,setEndValue]=React.useState(params.get('end') ?? new Date().toISOString().slice(0,16));
  const [page,setPage]=React.useState(1), [search,setSearch]=React.useState(''), [sort,setSort]=React.useState('usage');
  const [invoiceMonth,setInvoiceMonth]=React.useState(new Date().toISOString().slice(0,7));
  const [newSecret,setNewSecret]=React.useState('');
  const [alternativePlan,setAlternativePlan]=React.useState(''), [effectiveAt,setEffectiveAt]=React.useState('');
  const start = new Date(startValue), end = new Date(endValue);
  const range = `start=${encodeURIComponent(start.toISOString())}&end=${encodeURIComponent(end.toISOString())}`;
  const usage = useQuery({queryKey:['usage',granularity,startValue,endValue],queryFn:()=>fetchJson(`/reports/usage/time-series?account_id=${account}&${range}&granularity=${granularity}`),refetchInterval:5000,placeholderData:(previous)=>previous});
  const mtd = useQuery({queryKey:['mtd',account],queryFn:()=>fetchJson(`/reports/usage/mtd?account_id=${account}`),refetchInterval:5000});
  const accounts=useQuery({queryKey:['accounts',page,search,sort],queryFn:()=>fetchJson(`/accounts?page=${page}&page_size=10&search=${encodeURIComponent(search)}&sort=${sort}`)});
  const detail=useQuery({queryKey:['detail',account],queryFn:()=>fetchJson(`/accounts/${account}`)});
  const invoices=useQuery({queryKey:['invoices',account],queryFn:()=>fetchJson(`/invoices/${account}`)});
  const plans=useQuery({queryKey:['plans'],queryFn:()=>fetchJson('/plans')});
  const whatIf=useQuery({queryKey:['what-if',account,alternativePlan],queryFn:()=>fetchJson(`/accounts/${account}/what-if?plan_id=${alternativePlan}`),enabled:false});
  const preview=useQuery({queryKey:['invoice-preview',account,invoiceMonth],queryFn:()=>fetchJson(`/invoices/preview/${account}/${invoiceMonth}-01T00:00:00Z`),enabled:false});
  const keys=useQuery({queryKey:['keys',account],queryFn:()=>fetchJson(`/accounts/${account}/api-keys`)});
  const change=(g:string)=>{setGranularity(g);syncUrl(g,startValue,endValue)};
  const syncUrl=(g:string,s:string,e:string)=>{const q=new URLSearchParams({g,start:s,end:e});history.replaceState(null,'',`?${q}`)};
  React.useEffect(()=>{syncUrl(granularity,startValue,endValue)},[]);
  const createKey=async()=>{const r=await fetch(`${api}/accounts/${account}/api-keys`,{method:'POST',headers:{'X-Dashboard-Token':dashboard}});if(!r.ok)throw new Error('Key create failed');const d=await r.json();setNewSecret(d.secret);void keys.refetch()};
  const changePlan=async()=>{if(!alternativePlan)return;const when=effectiveAt?`&effective_at=${encodeURIComponent(new Date(effectiveAt).toISOString())}`:'';const r=await fetch(`${api}/accounts/${account}/plan-changes?plan_id=${alternativePlan}${when}`,{method:'POST',headers:{'X-Dashboard-Token':dashboard}});if(!r.ok){window.alert('Plan change failed. Choose a future time and try again.');return}setEffectiveAt('');void queryClient.invalidateQueries()};
  const revokeKey=async(id:string)=>{await fetch(`${api}/accounts/${account}/api-keys/${id}`,{method:'DELETE',headers:{'X-Dashboard-Token':dashboard}});void keys.refetch()};
  const points:Point[] = usage.data?.data ?? []; const max=Math.max(1,...points.map(p=>p.billable_calls));
  return <main className="mx-auto max-w-5xl p-8"><header className="mb-8 flex items-center justify-between"><div><p className="text-sm text-cyan-400">Metered billing</p><h1 className="text-3xl font-bold">Demo account</h1></div><div className="rounded bg-slate-800 p-1"><button onClick={()=>change('hour')} className={granularity==='hour'?'rounded bg-cyan-500 px-3 py-1 text-slate-950':'px-3 py-1'}>Hourly</button><button onClick={()=>change('day')} className={granularity==='day'?'rounded bg-cyan-500 px-3 py-1 text-slate-950':'px-3 py-1'}>Daily</button></div></header>
  <section className="mb-5 rounded bg-slate-900 p-4"><label>Dashboard access token <input type="password" value={dashboard} onChange={e=>setDashboard(e.target.value)} className="mx-2 rounded bg-slate-800 p-2" autoComplete="off"/></label><button onClick={()=>{sessionStorage.setItem('dashboardToken',dashboard);void queryClient.invalidateQueries()}} className="rounded bg-cyan-700 px-3 py-2">Connect</button></section>
  {mtd.isLoading ? <p>Loading account summary…</p> : mtd.isError ? <p className="text-rose-400">Could not load live billing data.</p> : <section className="mb-8 grid gap-4 md:grid-cols-3"><Card title="MTD calls" value={String(mtd.data.calls)}/><Card title="Allowance" value={String(mtd.data.included_calls)}/><Card title="Projected overage" value={`$${money(mtd.data.projected_overage_cents)}`}/></section>}
  <section className="mb-4 flex flex-wrap gap-3"><label>From <input type="datetime-local" value={startValue} onChange={e=>{setStartValue(e.target.value);syncUrl(granularity,e.target.value,endValue)}} className="rounded bg-slate-800 p-2"/></label><label>To <input type="datetime-local" value={endValue} onChange={e=>{setEndValue(e.target.value);syncUrl(granularity,startValue,e.target.value)}} className="rounded bg-slate-800 p-2"/></label></section>
  <section className="rounded-xl bg-slate-900 p-6 shadow"><h2 className="mb-4 text-xl font-semibold">Billable calls</h2>{usage.isLoading?<p>Loading chart…</p>:usage.isError?<p className="text-rose-400">Could not load usage.</p>:points.length===0?<p className="text-slate-400">No usage in this range.</p>:<svg role="img" aria-label="Billable calls over time" viewBox="0 0 900 240" className="h-56 w-full"><path d={`M 0 230 ${points.map((p,i)=>`L ${(i/Math.max(1,points.length-1))*900} ${220-(p.billable_calls/max)*190}`).join(' ')} L 900 230 Z`} fill="rgb(6 182 212 / 0.22)"/><path d={points.map((p,i)=>`${i===0?'M':'L'} ${(i/Math.max(1,points.length-1))*900} ${220-(p.billable_calls/max)*190}`).join(' ')} fill="none" stroke="rgb(34 211 238)" strokeWidth="3"/>{points.map((p,i)=><circle key={p.bucket} cx={(i/Math.max(1,points.length-1))*900} cy={220-(p.billable_calls/max)*190} r="3" fill="rgb(34 211 238)"><title>{`${new Date(p.bucket).toLocaleString()}: ${p.billable_calls} calls`}</title></circle>)}</svg>}</section>
  <section className="mt-8 rounded-xl bg-slate-900 p-6"><h2 className="text-xl font-semibold">Accounts</h2><div className="my-3 flex gap-2"><input placeholder="Search accounts" value={search} onChange={e=>{setPage(1);setSearch(e.target.value)}} className="rounded bg-slate-800 p-2"/><select value={sort} onChange={e=>setSort(e.target.value)} className="rounded bg-slate-800 p-2"><option value="usage">Usage</option><option value="name">Name</option></select></div>{accounts.isLoading?<p>Loading accounts…</p>:accounts.isError?<p>Unable to load accounts.</p>:accounts.data?.data?.length===0?<p>No matching accounts.</p>:<><p>{accounts.data?.data?.map((a:any)=><button key={a.id} onClick={()=>setAccount(a.id)} className={`mr-6 ${account===a.id?'text-cyan-300':'text-slate-200'}`}>{a.name} · {a.calls} calls</button>)}</p><button className="mt-3" onClick={()=>setPage(Math.max(1,page-1))}>Previous</button><span className="px-3">Page {page}</span><button onClick={()=>setPage(page+1)}>Next</button></>}</section>
  {detail.data&&<section className="mt-4 rounded-xl bg-slate-900 p-6"><h2 className="text-xl font-semibold">Account details · {detail.data.plan_name}</h2><p>{detail.data.calls}/{detail.data.included_calls} calls · projected ${money(detail.data.projected_overage_cents??0)}</p><progress value={detail.data.calls} max={detail.data.included_calls||1}/><pre className="mt-2 text-sm">{JSON.stringify(detail.data.endpoints,null,2)}</pre></section>}
  <section className="mt-4 rounded-xl bg-slate-900 p-6"><h2 className="text-xl font-semibold">Invoice preview</h2><input type="month" value={invoiceMonth} onChange={e=>setInvoiceMonth(e.target.value)} className="rounded bg-slate-800 p-2"/><button onClick={()=>void preview.refetch()} className="ml-2 rounded bg-cyan-700 px-3 py-1">Preview period</button>{preview.isError&&<p className="text-rose-300">Could not load preview.</p>}{preview.data&&<article className="mt-3"><p>{preview.data.plan_name} · {preview.data.calls} calls · base ${money(preview.data.monthly_base_fee_cents)}</p><p>Overage: {preview.data.overage_calls} calls · ${money(preview.data.overage_cents)}</p><p className="font-bold">Total: ${money(preview.data.total_cents)}</p><p>{preview.data.finalizable?'Period closed; invoice can be finalized.':'Preview only; period closes 48 hours after month end.'}</p>{preview.data.finalizable&&<button onClick={async()=>{await fetch(`${api}/invoices/${account}/${invoiceMonth}-01T00:00:00Z`,{method:'POST',headers:{'X-Dashboard-Token':dashboard}});void invoices.refetch()}} className="mt-2 rounded bg-emerald-700 px-3 py-1">Finalize invoice</button>}</article>}</section>
  <section className="mt-4 rounded-xl bg-slate-900 p-6"><h2 className="text-xl font-semibold">Plan comparison and changes</h2>{plans.isLoading?<p>Loading plans…</p>:plans.isError?<p className="text-rose-300">Unable to load plans.</p>:<><label>Alternative plan <select value={alternativePlan} onChange={e=>setAlternativePlan(e.target.value)} className="ml-2 rounded bg-slate-800 p-2"><option value="">Choose a plan</option>{plans.data?.data?.map((p:any)=><option key={p.id} value={p.id}>{p.name} · {p.included_calls.toLocaleString()} included</option>)}</select></label><button disabled={!alternativePlan||whatIf.isFetching} onClick={()=>void whatIf.refetch()} className="ml-2 rounded bg-cyan-700 px-3 py-1">Compare last 30 days</button>{whatIf.isError&&<p className="text-rose-300">Could not calculate comparison.</p>}{whatIf.data&&<p className="mt-3">{whatIf.data.calls.toLocaleString()} billable calls: {whatIf.data.current_plan_name} ${money(whatIf.data.current_cost_cents)} vs {whatIf.data.alternative_plan_name} ${money(whatIf.data.alternative_cost_cents)} ({whatIf.data.difference_cents>=0?'+':''}${money(whatIf.data.difference_cents)}).</p>}<div className="mt-4"><label>Effective time (leave blank for now) <input type="datetime-local" value={effectiveAt} onChange={e=>setEffectiveAt(e.target.value)} className="ml-2 rounded bg-slate-800 p-2"/></label><button disabled={!alternativePlan} onClick={()=>void changePlan()} className="ml-2 rounded bg-emerald-700 px-3 py-1">Schedule plan change</button><p className="mt-2 text-sm text-slate-400">Invoices prorate each plan’s allowance and base fee by the exact time it was active.</p></div></>}</section>
  <section className="mt-4 rounded-xl bg-slate-900 p-6"><h2 className="text-xl font-semibold">Invoices</h2><button onClick={()=>window.print()} className="rounded bg-cyan-700 px-3 py-1">Print / Save PDF</button>{invoices.isLoading?<p>Loading invoices…</p>:invoices.isError?<p>No invoice data available.</p>:invoices.data.data.length===0?<p>No invoices yet.</p>:invoices.data.data.map((i:any)=><article key={i.id} className="border-b border-slate-700 py-3">{new Date(i.period_start).toLocaleDateString()} · ${money(i.total_cents)} {i.lines?.map((l:any)=><p key={l.id}>{l.description}: ${money(l.amount_cents)}</p>)}</article>)}</section>
  <section className="mt-4 rounded-xl bg-slate-900 p-6"><h2 className="text-xl font-semibold">API keys</h2><button onClick={()=>void createKey()} className="rounded bg-cyan-700 px-3 py-1">Create key</button>{newSecret&&<p className="mt-2 break-all text-amber-300">Copy this secret now: {newSecret}</p>}{keys.isLoading?<p>Loading keys…</p>:keys.isError?<p>Unable to load API keys.</p>:keys.data?.data?.map((k:any)=><p key={k.id} className="mt-2">{k.prefix} · {k.revoked_at?'revoked':'active'} {!k.revoked_at&&<><button className="ml-2 text-rose-300" onClick={()=>void revokeKey(k.id)}>Revoke</button><button className="ml-2 text-cyan-300" onClick={async()=>{const r=await fetch(`${api}/accounts/${account}/api-keys/${k.id}/rotate?overlap_seconds=300`,{method:'POST',headers:{'X-Dashboard-Token':dashboard}});if(r.ok){const d=await r.json();setNewSecret(d.secret);void keys.refetch()}}}>Rotate</button></>}</p>)}</section></main>;
}
function Card({title,value}:{title:string,value:string}) { return <div className="rounded-xl bg-slate-900 p-5"><p className="text-sm text-slate-400">{title}</p><p className="mt-2 text-2xl font-bold">{value}</p></div> }
createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={new QueryClient()}><App/></QueryClientProvider></React.StrictMode>);
